home/urls.py
from django.urls import path,include
from . import views 
app_name ='home'
urlpatterns = [
   path('',views.index,name='hom'),
   path('about',views.about,name='abt'),
   path('conatct',views.contact,name='con'),
   path('academic',views.academic,name='aca'),
   path('student',views.student,name='std')
]

school/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls'))
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render (request,'index.html')

def about(request):
    return render (request,'about.html')

def contact(request):
    return render (request,'contact.html')

def academic(request):
    return render (request,'academic.html')

def student(request):
    return render (request,'student.html')

home/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles/mystyle.css' %}">
</head>
<body>
        <nav>
            <ul>
                <a href="">
                    <li class="logo">
                        <img src="{% static 'images/logo.png' %}" alt="">
                    </li>
                </a>
                <a href="{% url 'home:hom' %}">
                    <li class="home">
                        HOME
                    </li>
                </a>
                <a href="{% url 'home:abt' %}">
                    <li>
                        ABOUT US
                    </li>
                </a>
                <a href="{% url 'home:aca' %}">
                    <li>
                        ACADEMIC
                    </li>
                </a>
                <a href="{% url 'home:std' %}">
                    <li>
                        STUDENTS INFO
                    </li>
                </a>
                <a href="{% url 'home:con' %}">
                    <li>
                        CONTACT
                    </li>
                </a>
            </ul>
        </nav>
        <div class="col-lg-12 academic">
            ABOUT US
        </div>
        <div class="col-lg-6 back"></div>
        <div class="col-lg-6 contnt">
            <p class="size">The Kendriya Vidyalaya Sangathan (transl. Central School Organization) is a system of central government schools in India that are instituted under the aegis of the Ministry of Education, Government of India. As of July 2022, it has a total of 1,248 schools in India,<br> and three abroad in Moscow, Tehran and Kathmandu.<br> It is one of the world's largest chains of schools and also the largest chain of<br> schools in India is controlled by 25 Regional Offices and 05 ZIETs <br>(Zonal Institute of Education and Training) under KVS (HQ).</p>
        </div>
        <div class="col-lg-12">
            <p class="sizes">It is a system of central government schools in India and other countries[4] that have been instituted under the aegis of the Ministry of Education[5] and came into being in 1963 under the name Central Schools.[6] Later, the name was changed to Kendriya Vidyalaya. It is a non-profit organisation. Its schools are all affiliated to the Central Board of Secondary Education (CBSE).[4] Its objective is to educate children of the Indian Defence Services personnel who are often posted to remote locations. With the army starting its own Army Public Schools, the service was extended but not restricted to all central government employees.</p>
            <p class="sizes">A uniform curriculum is followed by schools all over India. By providing a common syllabus and system of education, the Kendriya Vidyalayas are intended to ensure that the children of government employees do not face education disadvantages when their parents are transferred from one location to another. The schools have been operational for more than 50 years.[7]

            </p>
            
        </div>
        <div class="col-lg-6">
            <p class="sizes"> As of July 2022, there were 1,251 schools named Kendriya Vidyalayas, having started with only 20 schools in the year 1963.[6] It is one of the largest school chains in world with 1,248 schools in India and three operated abroad.[4][8] A total of 14,30,442 students (as of 24 July 2022)[9] and 43,888 employees were on the rolls (as of 23 July 2022).[10] KVS has been recognized as an independent State by Bharat Scouts & Guides Movement as around 2,49,198 students enrolled as the Scouts, Guides, Cubs and Bulbuls.[9] These were divided among 25 regions, each headed by a deputy commissioner.[11] The three Kendriya Vidyalayas outside India is in Kathmandu, Moscow, and Tehran situated inside Embassies in these countries and their expenditures are borne by the Ministry of External Affairs.[6][12] They are intended for children of Indian embassy staff and other expatriate employees of the Government of India.[13]</p>

        </div>
        <div class="col-lg-6 campus"></div>
        <div class="col-lg-12">
            <p class="siz">The Kendriya Vidyalaya Sangathan or 'Central School Organisation'(as previously known), oversees the functioning of the schools with its headquarters in New Delhi.[4] The administration of this body is based on three levels. The chairman of Kendriya Vidyalaya Sangathan is always the Minister in Charge of the Ministry of Education of the Government of India; the deputy chairman is the Minister of State of the Ministry of Education. The real working power lies with the Commissioner of KVS. There are Additional Commissioners and Joint commissioners to accompany the Commissioner in the administration of KVS in different fields. The head of the KVs in a region is a Deputy Commissioner accompanied by two to three Assistant Commissioners. At present, there are 25 regional offices in KVS. There are individual principals of every KV, administrating the schools along with a Vice-Principal( wherever there is a vacancy for the post)and Head Master/ Mistress</p>
            <p class="siz">KVS also had the MP Quota which involved some special provision under which admissions are given.[15] Members of Lok Sabha & Rajya Sabha could recommend a few number of students for the admission. These Special Provisions only worked in KVs located in the constituency of the MP concerned. All members of parliament could recommend up to six students from their constituency for admission to a Kendriya Vidyalaya. From the academic session 2016–17, the quota had been increased to 10 students.[16] However, it is since the academic session 2022-23 all admission under special provisions like MP quota, Quota of Sponsoring agency( chairman quota ) have been made dysfunctional.</p>
            <p class="siz">The Quality Council of India (QCI) has accredited three of KV schools: KV RK Puram, KV IIT Powai and KV Bhinga.[17] The Kendriya Vidyalaya Gole Market school in Central Delhi has earned notice for upgrading to "E-Classroom" and e-Learning teaching processes with the implementation of Smart Boards in the classroom. This school produces an annual school magazine called Vidyalaya Patrika.[18]

                The organisation is one of the few schools that offers all varieties in sports, games, activities and the largest scope of subjects offered by CBSE to its students and is known for its holistic focus.[9]
                
                It has been felicitated with many awards by Government of India including the Rashtriya Khel Protsahan Puruskar in 2017 and Rajbhasha Kirti Puraskar on the occasion of Hindi Diwas in 2018-19</p>
                <p class="siz">All the schools share a common syllabus and offer bilingual instruction, in English and Hindi. They are co-educational. Sanskrit is taught as a compulsory subject from classes VI to VIII and as an optional subject until class XII. Students in classes VI to VIII could study the German language until November 2014, when the scheme was discontinued. But was again recontinued and is available in some schools until class 10. In Moscow, students are given an opportunity to choose French or Russian as their third or second language.

                    Tuition fees are charged for Kendriya Vidyalaya students have to pay the school development fund (Vidyalaya Vikas Nidhi), with the proceeds spent on the development of that particular school. Students from Scheduled Castes and Scheduled Tribes and children of KVS employees are exempt from tuition fees. Girls who are their parents' only child from class VI onward are exempt from tuition and school development fund.[14]</p>
        </div>
        <div class="footer">
            <div class="one">HELPFUL LINK<br><br>
              <li>www.cbse.nic.in</li>
              <li>www.ncert.nic.in</li>
              <li>www.cbseacademic.nic.in</li>
            </div>
            <div class="one">NAVIGATION<br><br>
            <li>About</li>
            <li>Academic</li>
            <li>Student Info</li>
            <li>Contact</li>
            </div>
            <div class="one">CONTACT<br><br>
            <li>Kendriya Vidyalaya No.1 New Building<br>Kozhikode,Kerala<br>Email id : kendriyavidyalaya@gmail.com<br>Phone No : 0496 264588</li></div>
        </div>
    </body>
</html>

home/templates/academic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles/mystyle.css' %}">
</head>
<body>
    <nav>
        <ul>
            <a href="">
                <li class="logo">
                    <img src="{% static 'images/logo.png' %}" alt="">
                </li>
            </a>
            <a href="{% url 'home:hom' %}">
                <li class="home">
                    HOME
                </li>
            </a>
            <a href="{% url 'home:abt' %}">
                <li>
                    ABOUT US
                </li>
            </a>
            <a href="{% url 'home:aca' %}">
                <li>
                    ACADEMIC
                </li>
            </a>
            <a href="{% url 'home:std' %}">
                <li>
                    STUDENTS INFO
                </li>
            </a>
            <a href="{% url 'home:con' %}">
                <li>
                    CONTACT
                </li>
            </a>
        </ul>
    </nav>
    <div class="col-lg-12 academic">
        ACADEMIC
        <p class="second">Our students always come out with flying colours in Academics.</p>
        <p class="third">In the last academic year 2016-17, in Std.XII, out of 118 students appeared, <br> students secured 90% and above, 83 got first class and 4 got second class.<br> In Std X, out of 146 students appeared, 132 students secured distinction, 14 got first class and 56 got A1 in all subjects.</p>
        <p class="forth">Many students who have passed out from our school are now pursuing their studies in most prestigious institutions. Some of them are:</p>
    </div>
    <table class="tab">
        <tr>
            <td>1</td>
            <td>Rohit</td>
            <td>IIT Bombay</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Vaishnavi</td>
            <td>IIT Bombay</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Ronal</td>
            <td>MBBS At JIPMER</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Rohit</td>
            <td>IIT Bombay</td>
        </tr>
        <tr>
            <td>5</td>
            <td>Rohit</td>
            <td>IIT Bombay</td>
        </tr>
        <tr>
            <td>1</td>
            <td>Rohit</td>
            <td>IIT Bombay</td>
        </tr>
        <tr>
            <td>1</td>
            <td>Rohit</td>
            <td>IIT Bombay</td>
        </tr>
        <tr>
            <td>1</td>
            <td>Rohit</td>
            <td>IIT Bombay</td>
        </tr>
        <tr>
            <td>1</td>
            <td>Rohit</td>
            <td>IIT Bombay</td>
        </tr>
        <tr>
            <td>1</td>
            <td>Rohit</td>
            <td>IIT Bombay</td>
        </tr>
        <tr>
            <td>1</td>
            <td>Rohit</td>
            <td>IIT Bombay</td>
        </tr>
        <tr>
            <td>1</td>
            <td>Rohit</td>
            <td>IIT Bombay</td>
        </tr>
        <tr>
            <td>1</td>
            <td>Rohit</td>
            <td>IIT Bombay</td>
        </tr>
        <tr>
            <td>1</td>
            <td>Rohit</td>
            <td>IIT Bombay</td>
        </tr>
    </table>
    <div class="footer">
        <div class="one">HELPFUL LINK<br><br>
          <li>www.cbse.nic.in</li>
          <li>www.ncert.nic.in</li>
          <li>www.cbseacademic.nic.in</li>
        </div>
        <div class="one">NAVIGATION<br><br>
        <li>About</li>
        <li>Academic</li>
        <li>Student Info</li>
        <li>Contact</li>
        </div>
        <div class="one">CONTACT<br><br>
        <li>Kendriya Vidyalaya No.1 New Building<br>Kozhikode,Kerala<br>Email id : kendriyavidyalaya@gmail.com<br>Phone No : 0496 264588</li></div>
    </div>
   
</body>
</html>

home/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles/mystyle.css' %}">
</head>
<body>
    <nav>
        <ul>
            <a href="">
                <li class="logo">
                    <img src="{% static 'images/logo.png' %}" alt="">
                </li>
            </a>
            <a href="{% url 'home:hom' %}">
                <li class="home">
                    HOME
                </li>
            </a>
            <a href="{% url 'home:abt' %}">
                <li>
                    ABOUT US
                </li>
            </a>
            <a href="{% url 'home:aca' %}">
                <li>
                    ACADEMIC
                </li>
            </a>
            <a href="{% url 'home:std' %}">
                <li>
                    STUDENTS INFO
                </li>
            </a>
            <a href="{% url 'home:con' %}">
                <li>
                    CONTACT
                </li>
            </a>
        </ul>
    </nav>
    <div class="col-lg-12 academic">
        CONTACT
    </div>
    <div>
    <h2>Phone No : 0496 264588</h2>
    <h2>Email id : kendriyavidyalaya@gmail.com</h2>
    </div>
    <div class="footer">
        <div class="one">HELPFUL LINK<br><br>
          <li>www.cbse.nic.in</li>
          <li>www.ncert.nic.in</li>
          <li>www.cbseacademic.nic.in</li>
        </div>
        <div class="one">NAVIGATION<br><br>
        <li>About</li>
        <li>Academic</li>
        <li>Student Info</li>
        <li>Contact</li>
        </div>
        <div class="one">CONTACT<br><br>
        <li>Kendriya Vidyalaya No.1 New Building<br>Kozhikode,Kerala<br>Email id : kendriyavidyalaya@gmail.com<br>Phone No : 0496 264588</li></div>
    </div>
</body>
</html>

home/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles/mystyle.css' %}">
</head>

<body>
    <nav>
        <ul>
            <a href="">
                <li class="logo">
                    <img src="{% static 'images/logo.png' %}" alt="">
                </li>
            </a>
            <a href="{% url 'home:hom' %}">
                <li class="home">
                    HOME
                </li>
            </a>
            <a href="{% url 'home:abt' %}">
                <li>
                    ABOUT US
                </li>
            </a>
            <a href="{% url 'home:aca' %}">
                <li>
                    ACADEMIC
                </li>
            </a>
            <a href="{% url 'home:std' %}">
                <li>
                    STUDENTS INFO
                </li>
            </a>
            <a href="{% url 'home:con' %}">
                <li>
                    CONTACT
                </li>
            </a>
        </ul>
    </nav>
    <div class="dance">
        <h1 class="heading">Welcome to Kendriya Vidyalaya </h1>
        <p>KENDRIYA VIDYALAYA SANGHATAN was established in 1965 <br> under the noble patronage of noted academicians
            comprising</p>
        <a href="">
            <button class="read">
                Read More
            </button>
        </a>

    </div>
    
    <div class="fcit">
        <p id="head">OUR FACILITIES</p>
        <div class="spec"></div>
        <p class="staff">EXPERIENCED STAFF</p>
        <p class="content">We have well experienced and competent staff and <br> they are guiding and supporting our students in all <br> fields.</p>

        <p class="lib"> E - LIBRARY</p>
        <p class="conts">In addition to a collection of wide variety of books,<br> we provide a digital library facility for the benefit of <br>students and staff.</p>

        <p class="bus">SCHOOL BUS SERVICE</p>
        <p class="cont">We have buses plying all the major routes. The <br> majority of students avail school bus facility.</p>

        <p class="act">OTHER ACTIVITIES</p>
        <p class="con">We are giving importance to Co-curricular activities<br> like Basketball, Rollerskating, Chess, Keyboard,<br> Taekwondo, Dance & music, Yoga classes and <br>coaching is given by experienced staff.</p>

    </div>
    <div class="middle">
        <div class="child">Management <img src="https://bhavansschoolchevayur.org/images/profile-icon.png" alt="" class="img"></div>
        <div class="child">Academic <img src="https://bhavansschoolchevayur.org/images/academic-icon.png" alt="" class="aca"></div>
        <div class="child">Students <img src="https://bhavansschoolchevayur.org/images/student-icon.png" alt="" class="std"></div>
        <div class="child">Facility <img src="https://bhavansschoolchevayur.org/images/facility-icon.png" alt="" class="fct"></div>
        <div class="child">PTA <img src="https://bhavansschoolchevayur.org/images/pta-icon.png" alt="" class="pta"></div>


    </div>
    <div class="col-sm-6 backg"></div>
    <div class="col-sm-6">
        <h1>PRINCIPAL'S MESSAGE</h1>
        <p class="abts">It is a great pleasure for me to welcome you to the Website of KENDRIYA VIDYALAYA SANGHATAN.<br> Ours is a green, eco-friendly campus, situated on a hill top, away from the turmoil of city life.<br>Our founder, laid great emphasis on promotion of Indian culture & heritage.</p>
        <p class="abts">We are committed to the cause of character building, personality development and promotion of values<br> through Value based education. Our aim is to produce not only good students but also good citizens.</p>
        <button class="rea">
            READ MORE

        </button>

    </div>
    <div class="mgm">
        <h1 class="covid">REFLEXIONS CovidReflex - 2022</h1>
        <img src="https://bhavansschoolchevayur.org/magazine/1.png" alt="" class="ref">
        <button class="dwd">
            DOWNLOAD MAGAZINE
        </button>
    </div>
    <div class="footer">
        <div class="one">HELPFUL LINK<br><br>
          <li>www.cbse.nic.in</li>
          <li>www.ncert.nic.in</li>
          <li>www.cbseacademic.nic.in</li>
        </div>
        <div class="one">NAVIGATION<br><br>
        <li>About</li>
        <li>Academic</li>
        <li>Student Info</li>
        <li>Contact</li>
        </div>
        <div class="one">CONTACT<br><br>
        <li>Kendriya Vidyalaya No.1 New Building<br>Kozhikode,Kerala<br>Email id : kendriyavidyalaya@gmail.com<br>Phone No : 0496 264588</li></div>
    </div>

</body>

</html>

home/templates/student.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles/mystyle.css' %}">
</head>
<body>
    <nav>
        <ul>
            <a href="">
                <li class="logo">
                    <img src="{% static 'images/logo.png' %}" alt="">
                </li>
            </a>
            <a href="{% url 'home:hom' %}">
                <li class="home">
                    HOME
                </li>
            </a>
            <a href="{% url 'home:abt' %}">
                <li>
                    ABOUT US
                </li>
            </a>
            <a href="{% url 'home:aca' %}">
                <li>
                    ACADEMIC
                </li>
            </a>
            <a href="{% url 'home:std' %}">
                <li>
                    STUDENTS INFO
                </li>
            </a>
            <a href="{% url 'home:con' %}">
                <li>
                    CONTACT
                </li>
            </a>
        </ul>
    </nav>
    <div class="col-lg-12 academic">
        STUDENTS INFO
    </div>
    <table class="tabs">
        <tr>
            <td><b>Class</b></td>
            <td><b>Section</b></td>
            <td><b>Boys</b></td>
            <td><b>Girls</b></td>
            <td><b>Total</b></td>
        </tr>
        <tr>
            <td><b>I-V</b></td>
            <td>04</td>
            <td>67</td>
            <td>57</td>
            <td>124</td>
        </tr>
        <tr>
            <td><b>VI-X</b></td>
            <td>04</td>
            <td>67</td>
            <td>57</td>
            <td>124</td>
        </tr>
        <tr>
            <td><b>XI-XII</b></td>
            <td>04</td>
            <td>67</td>
            <td>57</td>
            <td>124</td>
        </tr>
        <tr>
            <td><b>Total</b></td>
            <td>49</td>
            <td>960</td>
            <td>782</td>
            <td><b>1742</b></td>
        </tr>
        
    </table>
    <div class="footer">
        <div class="one">HELPFUL LINK<br><br>
          <li>www.cbse.nic.in</li>
          <li>www.ncert.nic.in</li>
          <li>www.cbseacademic.nic.in</li>
        </div>
        <div class="one">NAVIGATION<br><br>
        <li>About</li>
        <li>Academic</li>
        <li>Student Info</li>
        <li>Contact</li>
        </div>
        <div class="one">CONTACT<br><br>
        <li>Kendriya Vidyalaya No.1 New Building<br>Kozhikode,Kerala<br>Email id : kendriyavidyalaya@gmail.com<br>Phone No : 0496 264588</li></div>
    </div>

</body>
</html>